name = "GasDispersion"
uuid = "ac6af613-5479-4178-853e-9d66de417193"
authors = ["Allan Farrell <allanf@protonmail.com> and contributors"]
version = "0.3.0"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"

[extensions]
GasDispersionClapeyronExt = "Clapeyron"

[compat]
Clapeyron = "0.6"
DataInterpolations = "3.6, 4, 6, 7, 8"
RecipesBase = "1"
SpecialFunctions = "2"
julia = "1.3"

[extras]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
