name = "GasDispersion"
uuid = "ac6af613-5479-4178-853e-9d66de417193"
authors = ["Allan Farrell <allanf@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Interpolations = "0.13, 0.14"
SpecialFunctions = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
